version: "3.8" #la version di fichier écrits compatible à la version du docker utiliser
services: #description des différents service associée à notre projet
  db: #ici nopus avons la base de donnée
    image: mysql:latest #l'image
    container_name: db_docker_synfony #nom du container
    restart: always # il doit toujours redémarrer
    volumes: #spécifie le volume dans lequel les données doivent persister
      - db-data:/var/lib/mysql
    environment: # autorisation des comptes sans mot de passe facilite les connexion avec root sans mot de passe
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks: # le reseau utilisé
      - dev

  phpmyadmin: #container phpmyadmin pour voir ce qui se passe dans notre base de donnée
    image: phpmyadmin/phpmyadmin # l'image associée
    container_name: phpmyadmin_docker_synfony # nom du container
    restart: always # doit toujours redémarrer
    depends_on: #dépends de la base de donnée db
      - db
    ports: #il est viible sur le port 8080:80
      - 8080:80
    environment: #son hôte est le container db
      PMA_HOST: db
    networks:
      - dev

  #interception des mails avant de les envoyés

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_synfony # nom du container
    command: bin/maildev --web 80 -- smtp 25 --hide-extensions STARTTLS #evite les messsages d'erreurs dans le container
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev
  #on rajoute une nouveau service lié à notre dockerfile
  www:
    build: php # construire php(nom du repertoire qu'on a créer dans le dossier docker-compose)
    container_name: www_docker_synfony #nom du container
    ports:
      - "8082:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled #un repertoire créer qui permet de passer la configuration des vhosts à l'intérieure du container
      - ./:/var/www/ #####
    restart: always
    networks:
      - dev

# on précise ici le reseau dev et le volume db-data qui est utilisé par le container
networks:
  dev:

volumes:
  db-data:
